Docs update: quarkus/spring instead of WildFly/Tomcat, CS instead of DRL, workbench/ES is dead, ...
kiegroup/optaplanner-website pull request #370
Opened 2021-07-29 10:05 UTC by ge0ffrey

2021-07-29 10:06 UTC, ge0ffrey commented on content/localized/ja/UserGuide-chapter1.adoc
> -= Chapter 1. OptaPlanner イントロダクション
This Japanese user guide chapter 1 was hopelessly stale (Still pointing to version 6.4 images). It's better to not have it all.

2021-07-29 10:34 UTC, triceo requested changes
Please remove BAVET from the pictures. It lacks features to make it work with the vast majority of our exampes, and introduces the user to a choice that they really don't need to be making.

2021-08-02 11:27 UTC, ge0ffrey commented
@triceo In that architecture picture, Bavet needs to be there, as it shows how Drools relates to ConstraintStreams, there being a second implementation, and there needs to be an illustration how all that fits together. In all the text, we only mention Drools.

How about I add "(experimental)" next to Bavet?

2021-08-02 11:32 UTC, triceo commented
Actually, I think you don't need to mention Drools in terms of CS at all. It is an implementation detail, no need to share that with people. Especially for new folks - what is this Drools you speak of, why do I need to start looking it up?

2021-08-06 16:10 UTC, ge0ffrey commented
@triceo Bavet removed, should be ok to merge now

2021-08-07 05:52 UTC, triceo approved these changes

2021-08-07 05:52 UTC, merged