BXMSPROD-1973 Update GHA setup-java to v3
kiegroup/optaplanner-website pull request #570
Opened 2023-02-16 09:56 UTC by radtriste

2023-02-16 10:03 UTC, Ginxo requested changes
please check

2023-02-16 10:03 UTC, Ginxo commented on .github/workflows/main.yml
> +          distribution: temurin
```suggestion
        with:
          java-version: 11
          distribution: temurin
          check-latest: true          
```

2023-02-17 09:49 UTC, mbiarnes approved these changes

2023-02-20 07:56 UTC, Ginxo approved these changes
LGTM

2023-02-20 07:56 UTC, merged